import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:isar_community/isar.dart';

import '../../../../../injection/global_providers.dart';
import '../../mappers/customer_isar_mapper.dart';
import '../../models/customer_isar.dart';
import '../../models/customer_model.dart';
import 'customer_local_datasource.dart';

/// Isar-backed implementation of [CustomerLocalDataSource].
///
/// All Isar queries (`_isar.customerIsars.…`) live exclusively in this
/// file — no other layer imports `package:isar_community`. The mapper
/// at `customer_isar_mapper.dart` owns the `CustomerModel ↔ CustomerIsar`
/// round-trip; this file is the thin "send a typed query, hand a
/// typed result back" seam.
///
/// Lifecycle: a single instance is created by Riverpod via
/// [customerLocalDataSourceProvider] once at bootstrap and reused for
/// the entire process. The wrapped [Isar] is owned by
/// [isarInstanceProvider] in `lib/injection/global_providers.dart`;
/// that global throws [StateError] until `configureDependencies()`
/// overrides it with the real, opened Isar from `DatabaseService.open`.
///
/// ─── ID semantics inside the data layer ───────────────────────────
///   * Lookups by `id` go through `getByUuid` / `deleteByUuid`:
///     the unique + `replace: true` index on `CustomerIsar.uuid`
///     turns those into constant-time index hits and lets
///     `deleteByUuid` future-proof against silent link breaks.
///   * Writes go through `putByUuid` so re-saving a customer with an
///     unchanged business key correctly UPDATES the existing row
///     (resolver: delete-then-insert via the unique index) instead of
///     inserting a duplicate.
///   * The Isar-internal numeric [Id] never escapes this file — the
///     mapper drops it on the way back to the Model.
class CustomerLocalDataSourceImpl implements CustomerLocalDataSource {
  const CustomerLocalDataSourceImpl(this._isar);

  final Isar _isar;

  /// Typed collection accessor. Auto-generated by
  /// `isar_community_generator` (see
  /// `lib/features/customer/data/models/customer_isar.g.dart`).
  IsarCollection<CustomerIsar> get _customers => _isar.customerIsars;

  @override
  Future<CustomerModel?> getById(String id) async {
    final found = await _customers.getByUuid(id);
    return found?.toModel();
  }

  @override
  Future<List<CustomerModel>> getAll() async {
    final rows =
        await _customers.where().sortByCreatedAtDesc().findAll();
    return rows.map((i) => i.toModel()).toList(growable: false);
  }

  @override
  Future<void> save(CustomerModel model) async {
    await _isar.writeTxn(() async {
      // `putByUuid` honours the `@Index(unique: true, replace: true)`
      // on `CustomerIsar.uuid`: re-inserting a row whose uuid is
      // already present overwrites that row instead of creating a
      // duplicate. The internal `CustomerIsar.id` (Isar.autoIncrement
      // sentinel from the mapper) is overridden by Isar on insert.
      await _customers.putByUuid(model.toIsar());
    });
  }

  @override
  Future<void> delete(String id) async {
    await _isar.writeTxn(() async {
      // Idempotent: returns `false` if no row matches.
      await _customers.deleteByUuid(id);
    });
  }

  @override
  Future<List<CustomerModel>> search(String query) async {
    final trimmed = query.trim();
    if (trimmed.isEmpty) {
      // Mirror [SearchCustomersUseCase] fallback: empty queries
      // return "give me everyone" rather than an empty list, so the
      // search bar never produces a confusingly-blank page.
      return getAll();
    }
    final hits = await _customers
        .filter()
        .fullNameContains(trimmed, caseSensitive: false)
        .or()
        .phoneNumberContains(trimmed)
        .or()
        .emailContains(trimmed, caseSensitive: false)
        .or()
        .notesContains(trimmed, caseSensitive: false)
        .findAll();
    return hits.map((i) => i.toModel()).toList(growable: false);
  }
}

/// Riverpod binding (manual — no `@riverpod` codegen). Reads the
/// global [isarInstanceProvider] so that bootstrap can swap the Isar
/// instance via `ProviderContainer(overrides: [...])` without
/// touching this file.
///
/// Constructed exactly once for the lifetime of the
/// `ProviderContainer` — see
/// `lib/injection/feature_injection/customer_providers.dart`.
final customerLocalDataSourceProvider = Provider<CustomerLocalDataSource>(
  (ref) => CustomerLocalDataSourceImpl(ref.watch(isarInstanceProvider)),
);
