import 'package:isar_community/isar.dart';

import '../../../../customer/data/mappers/service_isar_mapper.dart';
import '../../../../customer/data/models/service_isar.dart';
import '../../../../customer/data/models/service_model.dart';
import 'service_local_datasource.dart';

/// Isar-backed implementation of [ServiceLocalDataSource].
///
/// All Isar queries (`_isar.serviceIsars.…`) live exclusively in this
/// file — no other layer (Repository, Use Case, Domain, Presentation)
/// imports `package:isar_community`. The mapper at
/// `service_isar_mapper.dart` (owned by the customer feature's data
/// layer for now, since the schema foundation lived there) owns the
/// `ServiceModel ↔ ServiceIsar` round-trip; this file is the thin
/// "send a typed query, hand a typed result back" seam.
///
/// Lifecycle: a single instance is created by Riverpod via
/// [serviceLocalDataSourceProvider] once at bootstrap and reused for the
/// entire process. The wrapped [Isar] is owned by
/// [isarInstanceProvider] in `lib/injection/global_providers.dart`;
/// that global throws [StateError] until `configureDependencies()`
/// overrides it with the real, opened Isar from `DatabaseService.open`.
///
/// ─── ID semantics inside the data layer ─────────────────────────────
///   * Lookups by `id` go through `getByUuid` / `deleteByUuid`: the
///     unique + `replace: true` index on `ServiceIsar.uuid` turns
///     those into constant-time index hits and lets `deleteByUuid`
///     future-proof against silent link breaks.
///   * Writes go through `putByUuid` so re-saving a service with an
///     unchanged business key correctly UPDATES the existing row
///     instead of inserting a duplicate.
///   * The Isar-internal numeric [Id] never escapes this file — the
///     mapper drops it on the way back to the Model.
///
/// Mirrors `customer_local_datasource_impl.dart` exactly; consult that
/// file for the cross-collection ID strategy rationale.
class ServiceLocalDataSourceImpl implements ServiceLocalDataSource {
  const ServiceLocalDataSourceImpl(this._isar);

  final Isar _isar;

  /// Typed collection accessor. Auto-generated by
  /// `isar_community_generator` (see
  /// `lib/features/customer/data/models/service_isar.g.dart`).
  IsarCollection<ServiceIsar> get _services => _isar.serviceIsars;

  @override
  Future<ServiceModel?> getById(String id) async {
    final found = await _services.getByUuid(id);
    return found?.toModel();
  }

  @override
  Future<List<ServiceModel>> getByCustomer(String customerUuid) async {
    // Sort by `startedAt` desc so recently active jobs surface first.
    // Nullable timestamps are valid (`startedAt == null` for pending
    // services); Isar's generated `sortByStartedAtDesc` handles
    // nulls deterministically.
    final rows = await _services
        .where()
        .customerUuidEqualTo(customerUuid)
        .sortByStartedAtDesc()
        .findAll();
    return rows.map((i) => i.toModel()).toList(growable: false);
  }

  @override
  Future<int> countAll() => _services.count();

  @override
  Future<void> save(ServiceModel model) async {
    await _isar.writeTxn(() async {
      // `putByUuid` honours the `@Index(unique: true, replace: true)`
      // on `ServiceIsar.uuid`: re-inserting a row whose uuid is
      // already present overwrites that row instead of creating a
      // duplicate. The internal `ServiceIsar.id` (`Isar.autoIncrement`
      // sentinel from the mapper) is overridden by Isar on insert.
      await _services.putByUuid(model.toIsar());
    });
  }

  @override
  Future<void> delete(String id) async {
    await _isar.writeTxn(() async {
      // Idempotent: returns `false` if no row matches.
      await _services.deleteByUuid(id);
    });
  }
}
