/// Localization barrel mirroring `lalafen/lib/config/l10n/l10n.dart`.
///
/// Two surfaces are exported:
///   * [AppLocalizations] (generated by `flutter gen-l10n` from the
///     ARB sources in this directory)
///   * [LocalizationX] extension on [BuildContext] — exposes the
///     `context.l10n.<key>` shortcut required by README §
///     Localization.
///
/// ARB sources live at `lib/config/l10n/app_fa.arb` (Persian MVP
/// source) and `lib/config/l10n/app_en.arb` (tool fallback; English
/// is not user-facing in MVP). The hand-authored stub at
/// `lib/config/l10n/arb/app_localizations.dart` was deleted in an
/// earlier task; the regenerated `app_localizations.dart` lives
/// alongside the ARB sources.
library;

export 'app_localizations.dart';
export 'l10n_extension.dart';
